### ISSUE TITLE
how to exchange nuget gold ?

### ISSUE THREAD

**Issue by tiphilou17** [FifouBE/EconomyInc#3]
When card is upgrade with micro, atm wireless ok but not change nugget gold ( to this mod) with gold changer, i dont understand how do make it.

**Comment by Florent98** [comment]
As it's an alpha version of the mod, the gold nugget is not implemented yet. Even tho the items and blocks are available they are not functional for now. I'm currently fixing in order what needs to be fixed. Here is the roadmap .

**RoadMap**

- [✔] FIX BILLS STORAGE
- [✔] LIGHTING THE TESR MODELS (FIXED partially, no lightmap, so everything is bright, need to add a bit of light)
- [✔] GEAR AND GEAR MECHANISM ITEMS
- [✔] FIX RECIPES
- [✔] PACKETS OF DIFFERENT BILLS
- [✔] DIGITAL VAULT CRACKER (Partially)
- [✔] BLOCK SELLER DISPLAYING ITEM 3D (Fixed but currently is glitching out for some reason)
- [] GOLD NUGGET WEIGHT + REMOVE RECIPE ?
- [] GOLD CHANGER WORKING
- [] BLOCK SAFE VAULT FOR VILLAGES
- [] VILLAGES IMPLEMENTATION OF BANK + TABLE LIST
- [] COMMAND PLOTS
- [] PLOTS SAVING (WORLD SAVED DATA)
- [] CREATE INFORMER VILLAGER
- [] MYSQL

I'll keep this question open so as soon as I finished something I'll update the road map :)

Thanks

**Comment by tiphilou17** [comment]
ok, thx to this faster news. GOOD LUCK ITS A GREAT Job !

**Comment by Florent98** [comment]
Thanks for posting that comment, it allowed me to put that roadmap somewhere!
